linters:
  enable-all: true
  disable:
    - wsl
    - tparallel
    - gomnd
    - tagliatelle
    - dupl
    - godox
    - gochecknoglobals
    - paralleltest
    - gochecknoinits
    - nakedret
    - funlen
    - godot
    - gci
    - forbidigo
    - ineffassign
    - wrapcheck
    - nonamedreturns
    - nosprintfhostport
    - containedctx
    - varnamelen
    - stylecheck
    - ireturn
    - err113
    - exhaustruct
    - depguard
    - contextcheck
    - exhaustive
    - revive
    - errorlint
    - errname
    - unused
    - errchkjson
    - unparam
    - tagalign
    - gosec
    - thelper
    - makezero
    - perfsprint
    - mnd
  fast: false
