linters:
  enable-all: true
  disable:
    - scopelint
    - maligned
    - wsl
    - tparallel
    - gomnd
    - tagliatelle
    - dupl
    - godox
    - gochecknoglobals
    - paralleltest
    - gochecknoinits
    - nakedret
    - funlen
    - godot
    - gci
    - forbidigo
    - ineffassign
    - ifshort
    - wrapcheck
    - nonamedreturns
    - nosprintfhostport
    - containedctx
    - varnamelen
    - stylecheck
    - ireturn
    - goerr113
    - exhaustivestruct
    - golint
    - exhaustruct
    - depguard
    - contextcheck
    - nosnakecase
    - varcheck
    - interfacer
    - deadcode
    - golint
    - structcheck
    - exhaustive
    - revive
    - errorlint
    - errname
    - unused
    - errchkjson
    - unparam
    - tagalign
    - gosec
    - thelper
  fast: false
